name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.CR_PAT }}

            - name: Build and push Docker image
              run: |
                  docker build -t ghcr.io/${{ github.repository_owner }}/mrwigyfr:latest .
                  docker push ghcr.io/${{ github.repository_owner }}/mrwigyfr:latest

            - name: Deploy to VPS
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.CR_PAT }}
                      docker pull ghcr.io/${{ github.repository_owner }}/mrwigyfr:latest
                      docker stop mrwigyfr || true && docker rm mrwigyfr || true
                      docker run -d --name mrwigyfr -p 81:80 ghcr.io/${{ github.repository_owner }}/mrwigyfr:latest
                      docker image prune -f
